## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
%matplotlib inline
sns.set(color_codes=True)

## Importing the dataset

In [6]:
file_path = 'data_banknote_authentication.txt'
dataset = pd.read_csv(file_path,delimiter=',',header=None)
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [7]:
print(x)

[[  3.6216    8.6661   -2.8073   -0.44699]
 [  4.5459    8.1674   -2.4586   -1.4621 ]
 [  3.866    -2.6383    1.9242    0.10645]
 ...
 [ -3.7503  -13.4586   17.5932   -2.7771 ]
 [ -3.5637   -8.3827   12.393    -1.2823 ]
 [ -2.5419   -0.65804   2.6842    1.1952 ]]


In [8]:
print(y)

[0 0 0 ... 1 1 1]


In [9]:
print(dataset.head(10))

         0       1        2        3  4
0  3.62160  8.6661 -2.80730 -0.44699  0
1  4.54590  8.1674 -2.45860 -1.46210  0
2  3.86600 -2.6383  1.92420  0.10645  0
3  3.45660  9.5228 -4.01120 -3.59440  0
4  0.32924 -4.4552  4.57180 -0.98880  0
5  4.36840  9.6718 -3.96060 -3.16250  0
6  3.59120  3.0129  0.72888  0.56421  0
7  2.09220 -6.8100  8.46360 -0.60216  0
8  3.20320  5.7588 -0.75345 -0.61251  0
9  1.53560  9.1772 -2.27180 -0.73535  0


In [10]:
# Use the type() function to determine the data type of each object
print("Type of the data:", type(dataset))

Type of the data: <class 'pandas.core.frame.DataFrame'>


In [11]:
## View the last few rows of the data frame
print(dataset.tail(5))


            0         1        2        3  4
1367  0.40614   1.34920  -1.4501 -0.55949  1
1368 -1.38870  -4.87730   6.4774  0.34179  1
1369 -3.75030 -13.45860  17.5932 -2.77710  1
1370 -3.56370  -8.38270  12.3930 -1.28230  1
1371 -2.54190  -0.65804   2.6842  1.19520  1


In [12]:
#Getting the dimension of the data
print(dataset.shape)

(1372, 5)


In [13]:
duplicate_rows_df = dataset[dataset.duplicated()]
print("number of duplicate rows: ", duplicate_rows_df.shape)

number of duplicate rows:  (24, 5)


In [14]:
dataset.count()

0    1372
1    1372
2    1372
3    1372
4    1372
dtype: int64

In [21]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=0, train_size = .75)

#Decison Tree

In [22]:
from sklearn.tree import DecisionTreeRegressor
reg = DecisionTreeRegressor(max_depth = 2, random_state = 0)

In [23]:
reg.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=2, random_state=0)

In [27]:
y_pred = reg.predict(X_test)

In [30]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

0.07790836883318943

In [31]:
from sklearn.linear_model import LogisticRegression
logisticRegr = LogisticRegression()
logisticRegr.fit(X_train, y_train)

LogisticRegression()

In [33]:
y_pred = logisticRegr.predict(X_test)

In [34]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

0.014577259475218658

In [36]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9854227405247813

#SVM

In [39]:
from sklearn import svm
clf = svm.SVC(kernel='linear')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [40]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

0.014577259475218658

In [41]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9854227405247813

#Naive Bayes

In [42]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)

In [43]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

0.17201166180758018

In [44]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8279883381924198